//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapDefectDetector.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Settings_OvalityDefectPath {
            get {
                return ((string)(this["Settings_OvalityDefectPath"]));
            }
            set {
                this["Settings_OvalityDefectPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Settings_InclusionDefectPath {
            get {
                return ((string)(this["Settings_InclusionDefectPath"]));
            }
            set {
                this["Settings_InclusionDefectPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Settings_PaintDefectPath {
            get {
                return ((string)(this["Settings_PaintDefectPath"]));
            }
            set {
                this["Settings_PaintDefectPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Settings_ObloyDefectPath {
            get {
                return ((string)(this["Settings_ObloyDefectPath"]));
            }
            set {
                this["Settings_ObloyDefectPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Settings_UnderfillDefectPath {
            get {
                return ((string)(this["Settings_UnderfillDefectPath"]));
            }
            set {
                this["Settings_UnderfillDefectPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Settings_BreakerOffset {
            get {
                return ((string)(this["Settings_BreakerOffset"]));
            }
            set {
                this["Settings_BreakerOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Settings_CameraOffset {
            get {
                return ((string)(this["Settings_CameraOffset"]));
            }
            set {
                this["Settings_CameraOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Settings_BreakingTime {
            get {
                return ((string)(this["Settings_BreakingTime"]));
            }
            set {
                this["Settings_BreakingTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Settings_OvalityThreshold {
            get {
                return ((string)(this["Settings_OvalityThreshold"]));
            }
            set {
                this["Settings_OvalityThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Settings_InclusionThreshold {
            get {
                return ((string)(this["Settings_InclusionThreshold"]));
            }
            set {
                this["Settings_InclusionThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Settings_MinAreaInclusion {
            get {
                return ((string)(this["Settings_MinAreaInclusion"]));
            }
            set {
                this["Settings_MinAreaInclusion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Settings_MaxAreaInclusion {
            get {
                return ((string)(this["Settings_MaxAreaInclusion"]));
            }
            set {
                this["Settings_MaxAreaInclusion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Settings_MinAreaInpaintDefect {
            get {
                return ((string)(this["Settings_MinAreaInpaintDefect"]));
            }
            set {
                this["Settings_MinAreaInpaintDefect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Settings_MinInpaintWhiteThreshold {
            get {
                return ((string)(this["Settings_MinInpaintWhiteThreshold"]));
            }
            set {
                this["Settings_MinInpaintWhiteThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Settings_MinAreaObloy {
            get {
                return ((string)(this["Settings_MinAreaObloy"]));
            }
            set {
                this["Settings_MinAreaObloy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Settings_WidthFrame {
            get {
                return ((string)(this["Settings_WidthFrame"]));
            }
            set {
                this["Settings_WidthFrame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Settings_HeightFrame {
            get {
                return ((string)(this["Settings_HeightFrame"]));
            }
            set {
                this["Settings_HeightFrame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Settings_ExposureFrame {
            get {
                return ((string)(this["Settings_ExposureFrame"]));
            }
            set {
                this["Settings_ExposureFrame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Settings_SaturationFrame {
            get {
                return ((string)(this["Settings_SaturationFrame"]));
            }
            set {
                this["Settings_SaturationFrame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Settings_IpAdressCamera {
            get {
                return ((string)(this["Settings_IpAdressCamera"]));
            }
            set {
                this["Settings_IpAdressCamera"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Settings_IpAdressPr {
            get {
                return ((string)(this["Settings_IpAdressPr"]));
            }
            set {
                this["Settings_IpAdressPr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Settings_PortPr {
            get {
                return ((string)(this["Settings_PortPr"]));
            }
            set {
                this["Settings_PortPr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Settings_LastCycleTime {
            get {
                return ((string)(this["Settings_LastCycleTime"]));
            }
            set {
                this["Settings_LastCycleTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Settings_CoefCapRadiusInclusion {
            get {
                return ((string)(this["Settings_CoefCapRadiusInclusion"]));
            }
            set {
                this["Settings_CoefCapRadiusInclusion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Settings_СorrugationsCountForUnderFill {
            get {
                return ((string)(this["Settings_СorrugationsCountForUnderFill"]));
            }
            set {
                this["Settings_СorrugationsCountForUnderFill"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Settings_СoefCapRadiusUnderFill {
            get {
                return ((string)(this["Settings_СoefCapRadiusUnderFill"]));
            }
            set {
                this["Settings_СoefCapRadiusUnderFill"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Settings_LastDefectSettingsFileName {
            get {
                return ((string)(this["Settings_LastDefectSettingsFileName"]));
            }
            set {
                this["Settings_LastDefectSettingsFileName"] = value;
            }
        }
    }
}
