//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapDefectDetector.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Settings_IpAdressCamera {
            get {
                return ((string)(this["Settings_IpAdressCamera"]));
            }
            set {
                this["Settings_IpAdressCamera"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Settings_IpAdressPr {
            get {
                return ((string)(this["Settings_IpAdressPr"]));
            }
            set {
                this["Settings_IpAdressPr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Settings_PortPr {
            get {
                return ((string)(this["Settings_PortPr"]));
            }
            set {
                this["Settings_PortPr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Settings_LastCycleTime {
            get {
                return ((string)(this["Settings_LastCycleTime"]));
            }
            set {
                this["Settings_LastCycleTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Settings_LastDefectSettingsFileName {
            get {
                return ((string)(this["Settings_LastDefectSettingsFileName"]));
            }
            set {
                this["Settings_LastDefectSettingsFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Settings_LastRecipeFileName {
            get {
                return ((string)(this["Settings_LastRecipeFileName"]));
            }
            set {
                this["Settings_LastRecipeFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Settings_LastPrSettingsFileName {
            get {
                return ((string)(this["Settings_LastPrSettingsFileName"]));
            }
            set {
                this["Settings_LastPrSettingsFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Settings_LastCameraSettingsFileName {
            get {
                return ((string)(this["Settings_LastCameraSettingsFileName"]));
            }
            set {
                this["Settings_LastCameraSettingsFileName"] = value;
            }
        }
    }
}
